/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#161e00",
        "surface-bright": "#37374d",
        "surface": "#111225",
        "on-primary-container": "#006a71",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#3c4d00",
        "primary": "#e1fdff",
        "primary-fixed": "#74f5ff",
        "secondary-fixed": "#f8d8ff",
        "secondary-container": "#b600f8",
        "surface-dim": "#111225",
        "on-tertiary-container": "#516800",
        "on-background": "#e1e0fb",
        "on-primary-fixed-variant": "#004f54",
        "primary-fixed-dim": "#00dbe7",
        "surface-container-highest": "#323348",
        "on-surface": "#e1e0fb",
        "on-primary": "#00363a",
        "on-secondary-fixed-variant": "#74009f",
        "surface-container": "#1d1e32",
        "surface-container-high": "#27283d",
        "surface-container-lowest": "#0b0c1f",
        "surface-container-low": "#191a2d",
        "inverse-on-surface": "#2e2f43",
        "tertiary-fixed-dim": "#abd600",
        "primary-container": "#00f2ff",
        "on-error": "#690005",
        "error-container": "#93000a",
        "surface-tint": "#00dbe7",
        "surface-variant": "#323348",
        "outline-variant": "#3a494b",
        "tertiary-container": "#bdec00",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#c3f400",
        "on-tertiary": "#283500",
        "secondary": "#ebb2ff",
        "on-secondary-fixed": "#320047",
        "on-surface-variant": "#b9cacb",
        "on-secondary": "#520072",
        "outline": "#849495",
        "secondary-fixed-dim": "#ebb2ff",
        "inverse-surface": "#e1e0fb",
        "on-secondary-container": "#fff6fc",
        "inverse-primary": "#00696f",
        "tertiary": "#efffbb",
        "on-primary-fixed": "#002022",
        "background": "#111225"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "40px",
        "gutter": "20px",
        "unit": "4px",
        "margin-mobile": "16px",
        "xs": "4px",
        "lg": "24px",
        "sm": "8px",
        "2xl": "64px",
        "md": "16px",
        "margin-desktop": "48px"
      },
      fontFamily: {
        "body-lg": ["Geist", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "headline-md": ["Sora", "sans-serif"],
        "display-lg": ["Sora", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Sora", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
